import { useEffect, useState } from 'react'
import Artwork from '../components/Artwork'
import TrackActionSheet from '../components/TrackActionSheet'
import useLongPress from '../hooks/useLongPress'
import { createStation, getAlbumQueue, getAlbumTracks, getStationQueue, mediaUrl, type AlbumSummary, type Track } from '../api'
import { usePlayback, type QueueSource } from '../state/PlaybackContext'
import { trackToNowPlaying } from '../utils/mediaMappers'

export default function AlbumDetailPage({ album, onBack }: { album: AlbumSummary; onBack: () => void }) {
  const [tracks, setTracks] = useState<Track[]>([])
  const [actionTrack, setActionTrack] = useState<Track | null>(null)
  const { playQueue } = usePlayback()
  useEffect(() => { void getAlbumTracks(album.artist, album.title).then(setTracks) }, [album])
  const queue = tracks.map(track => trackToNowPlaying(track))
  const playAlbum = (shuffle = false) => void getAlbumQueue(album.artist, album.title, 500, shuffle).then(r => playQueue(r.queue.map(track => trackToNowPlaying(track))))
  const handleStartRadio = (track: Track) => { const stationName = `${track.title} Radio`; void getStationQueue('song', String(track.id)).then(r => playQueue(r.queue.map(t => trackToNowPlaying(t, { stationName })), 0, { kind: 'station', stationType: 'song', seedValue: String(track.id), stationName } satisfies QueueSource)) }
  const handleSaveStation = (track: Track) => { void createStation(`${track.title} Radio`, 'song', String(track.id), track.id).catch(() => {}) }
  return <div><button onClick={onBack} style={{ display: 'flex', alignItems: 'center', gap: 6, padding: '10px 0', marginBottom: 16, minHeight: 44, color: 'var(--text-secondary)', fontSize: 14, fontWeight: 500 }}>&larr; Back to Library</button><div className="page-title-centered"><div style={{ display: 'grid', placeItems: 'center', width: '100%' }}><Artwork src={mediaUrl('/api/media/albums/cover?artist=' + encodeURIComponent(album.artist) + '&album=' + encodeURIComponent(album.title))} label={album.title} size={150} /></div><h1 style={{ marginTop: 16 }}>{album.title}</h1><p style={{ color: 'var(--text-muted)', fontSize: 13 }}>{album.artist} {'\u00b7'} {album.track_count} {album.track_count === 1 ? 'track' : 'tracks'}</p><div style={{ display: 'flex', justifyContent: 'center', gap: 10, marginTop: 16, flexWrap: 'wrap' }}><button onClick={() => playAlbum(false)} style={{ padding: '11px 18px', borderRadius: 'var(--radius-pill)', background: 'var(--accent-primary)', color: '#fff', fontWeight: 800 }}>Play Album</button><button onClick={() => playAlbum(true)} style={{ padding: '11px 18px', borderRadius: 'var(--radius-pill)', background: 'var(--bg-surface)', color: 'var(--text-primary)', fontWeight: 800 }}>Shuffle</button></div></div><p className="section-label" style={{ marginTop: 28 }}>Tracks</p>{tracks.map((track, i) => <AlbumTrackRow key={track.id} track={track} index={i} onPlay={() => playQueue(queue, i)} onAction={() => setActionTrack(track)} />)}<TrackActionSheet open={!!actionTrack} track={actionTrack} onClose={() => setActionTrack(null)} onStartRadio={handleStartRadio} onSaveStation={handleSaveStation} /></div>
}
function AlbumTrackRow({ track, index, onPlay, onAction }: { track: Track; index: number; onPlay: () => void; onAction: () => void }) { const longPress = useLongPress(onAction); return <div className="card-premium" style={{ width: '100%', padding: 12, marginBottom: 7, textAlign: 'left', display: 'flex', alignItems: 'center', gap: 8 }} {...longPress}><button onClick={onPlay} style={{ flex: 1, minWidth: 0, textAlign: 'left' }}><strong>{index + 1}. {track.title}</strong><span style={{ display: 'block', fontSize: 12, color: 'var(--text-muted)' }}>{track.artist}</span></button><button className="track-overflow-button" aria-label="Track actions" onClick={(event) => { event.stopPropagation(); onAction() }}>⋯</button></div> }