import { useEffect, useState } from 'react'
import Artwork from '../components/Artwork'
import LoadingSkeleton from '../components/LoadingSkeleton'
import PageError from '../components/PageError'
import TrackActionSheet from '../components/TrackActionSheet'
import useLongPress from '../hooks/useLongPress'
import { getAlbumQueue, getArtistDetail, getArtistQueue, getArtistTracks, mediaUrl, type AlbumSummary, type ArtistDetail, type Track } from '../api'
import { useRadioActions } from '../hooks/useRadioActions'
import { usePlayback } from '../state/PlaybackContext'
import { trackToNowPlaying } from '../utils/mediaMappers'

export default function ArtistDetailPage({ artist, onBack, onOpenAlbum }: { artist: string; onBack: () => void; onOpenAlbum: (a: AlbumSummary) => void }) {
  const [detail, setDetail] = useState<ArtistDetail | null>(null), [songs, setSongs] = useState<Track[]>([]), [offset, setOffset] = useState(0), [hasMore, setHasMore] = useState(false), [loading, setLoading] = useState(true), [error, setError] = useState<string | null>(null), [actionTrack, setActionTrack] = useState<Track | null>(null)
  const { playQueue } = usePlayback()
  const { startSongRadio, saveSongStation, startArtistRadio } = useRadioActions()
  const play = (tracks: Track[], i = 0) => playQueue(tracks.map(t => trackToNowPlaying(t)), i)
  const load = () => { setLoading(true); setError(null); Promise.all([getArtistDetail(artist), getArtistTracks(artist, 50, 0)]).then(([d, p]) => { setDetail(d); setSongs(p.items); setOffset(p.items.length); setHasMore(p.has_more) }).catch(() => setError('Could not load artist.')).finally(() => setLoading(false)) }
  useEffect(load, [artist])
  if (loading) return <LoadingSkeleton rows={6} />
  if (error || !detail) return <PageError message={error ?? 'Artist not found.'} onRetry={load} />
  const more = () => void getArtistTracks(artist, 50, offset).then(p => { setSongs([...songs, ...p.items]); setOffset(offset + p.items.length); setHasMore(p.has_more) })
  const radio = () => startArtistRadio(detail.name)
  const shuffle = () => void getArtistQueue(detail.name, Math.max(detail.track_count, 1000), true).then(r => play(r.queue))
  return <div><button onClick={onBack} style={{ display: 'flex', alignItems: 'center', gap: 6, padding: '10px 0', marginBottom: 16, minHeight: 44, color: 'var(--text-secondary)', fontSize: 14, fontWeight: 500 }}>&larr; Library</button><div style={{ marginBottom: 20 }}><h1 style={{ fontSize: '2rem', fontWeight: 800, letterSpacing: '-0.03em', marginBottom: 4 }}>{detail.name}</h1><p style={{ fontSize: 13, color: 'var(--text-muted)' }}>{detail.track_count} {detail.track_count === 1 ? 'track' : 'tracks'} {'\u00b7'} {detail.album_count} {detail.album_count === 1 ? 'album' : 'albums'}</p><div style={{ display: 'flex', gap: 10, marginTop: 16 }}><button onClick={radio} style={{ flex: 1, height: 46, borderRadius: 'var(--radius-m)', background: 'var(--accent-primary)', color: '#fff', fontWeight: 700, fontSize: 14, boxShadow: '0 4px 16px var(--accent-primary-glow)' }}>Play Artist Radio</button><button onClick={shuffle} style={{ flex: 1, height: 46, borderRadius: 'var(--radius-m)', background: 'var(--bg-surface)', border: '1px solid var(--border-subtle)', color: 'var(--text-primary)', fontWeight: 700, fontSize: 14 }}>Shuffle Artist</button></div></div><p className="section-label">Albums</p><div style={{ display: 'grid', gap: 10, marginBottom: 24 }}>{detail.albums.map(a => <div key={a.title} className="card-premium" style={{ padding: '10px 14px', display: 'flex', gap: 12, alignItems: 'center' }}><button onClick={() => onOpenAlbum(a)} style={{ display: 'flex', gap: 12, alignItems: 'center', flex: 1, minWidth: 0, textAlign: 'left' }}><Artwork src={mediaUrl('/api/media/albums/cover?artist=' + encodeURIComponent(a.artist) + '&album=' + encodeURIComponent(a.title))} label={a.title} size={52} /><span style={{ minWidth: 0 }}><strong style={{ display: 'block', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{a.title}</strong><span style={{ fontSize: 12, color: 'var(--text-muted)' }}>{a.year ?? ''} {a.year ? '\u00b7 ' : ''}{a.track_count} {a.track_count === 1 ? 'track' : 'tracks'}</span></span></button><button onClick={() => void getAlbumQueue(a.artist, a.title).then(r => play(r.queue))} style={{ padding: '8px 12px', borderRadius: 'var(--radius-pill)', background: 'var(--accent-primary)', color: '#fff', fontSize: 12, fontWeight: 700 }}>Play</button></div>)}</div><p className="section-label">Songs</p><div style={{ display: 'grid', gap: 7 }}>{songs.map((t, i) => <ArtistTrackRow key={String(t.id) + '-' + i} track={t} onPlay={() => play(songs, i)} onAction={() => setActionTrack(t)} />)}</div>{hasMore && <button onClick={more} className="card-premium" style={{ width: '100%', padding: 14, marginTop: 10, color: 'var(--accent-primary)', fontWeight: 800 }}>Load More Songs</button>}<TrackActionSheet open={!!actionTrack} track={actionTrack} onClose={() => setActionTrack(null)} onGoToAlbum={track => onOpenAlbum({ title: track.album, artist: track.artist, track_count: 0 })} onStartRadio={startSongRadio} onSaveStation={saveSongStation} /></div>
}
function ArtistTrackRow({ track, onPlay, onAction }: { track: Track; onPlay: () => void; onAction: () => void }) { const longPress = useLongPress(onAction); return <div className="card-premium" style={{ padding: 12, textAlign: 'left', display: 'flex', alignItems: 'center', gap: 8 }} {...longPress}><button onClick={onPlay} style={{ flex: 1, minWidth: 0, textAlign: 'left' }}><strong style={{ display: 'block', fontSize: 14 }}>{track.title}</strong><span style={{ fontSize: 12, color: 'var(--text-muted)' }}>{track.album}</span></button><button className="track-overflow-button" aria-label="Track actions" onClick={(event) => { event.stopPropagation(); onAction() }}>&#8943;</button></div> }

