import { useEffect, useState } from 'react'
import { favoriteAudiobook, getAudiobook, getAudiobookSummary, getAudiobooks, mediaUrl, type Audiobook, type AudiobookDetail, type AudiobookSummary, type Chapter } from '../api'
import { usePlayback, type NowPlaying } from '../state/PlaybackContext'
const empty:AudiobookSummary={available:0,not_started:0,in_progress:0,finished:0,favorites:0,total_listening_seconds:0};const item=(b:AudiobookDetail,c:Chapter):NowPlaying=>({mode:'audiobook',id:c.id,title:b.title,subtitle:c.title,streamUrl:mediaUrl(c.stream_url),durationSeconds:c.duration_seconds,audiobookId:b.id,chapterId:c.id,coverUrl:mediaUrl(`/api/media/audiobooks/${b.id}/cover`)})
export default function BookshelfPage(){const [summary,setSummary]=useState(empty),[books,setBooks]=useState<Audiobook[]>([]),[detail,setDetail]=useState<AudiobookDetail|null>(null);const {playQueue}=usePlayback();const refresh=()=>void Promise.all([getAudiobookSummary(),getAudiobooks()]).then(([s,b])=>{setSummary(s);setBooks(b)});useEffect(refresh,[]);if(detail){const start=Math.max(0,detail.chapters.findIndex(c=>c.id===detail.latest_progress?.chapter_id));const play=(index=start)=>playQueue(detail.chapters.map(c=>item(detail,c)),index);const toggle=async()=>{await favoriteAudiobook(detail.id);setDetail(await getAudiobook(detail.id));refresh()};return <div><button onClick={()=>setDetail(null)} style={{marginBottom:18,color:'var(--text-secondary)'}}>‹ Bookshelf</button><h1 style={{fontSize:'1.8rem',fontWeight:800,marginBottom:4}}>{detail.title}</h1><p style={{color:'var(--text-muted)',marginBottom:12}}>{detail.author}</p><div className="card-premium" style={{padding:16,marginBottom:20}}><strong>{detail.status.replace('_',' ')}</strong><p style={{fontSize:12,color:'var(--text-muted)',margin:'6px 0 14px'}}>{detail.latest_progress?`${Math.round(detail.latest_progress.progress_percent)}% complete`:'Not started'}</p><button onClick={()=>play()} style={{padding:'10px 15px',borderRadius:18,background:'var(--accent-primary)',color:'#fff',marginRight:8}}>Continue</button><button onClick={()=>void toggle()} style={{padding:'10px 15px',borderRadius:18}}>{detail.favorite?'? Favorited':'? Favorite'}</button></div><p className="section-label">Chapters</p>{detail.chapters.map((c,i)=><button onClick={()=>play(i)} className="card-premium" style={{padding:14,textAlign:'left',width:'100%',marginBottom:8,color:'var(--text-primary)'}} key={c.id}><strong>{c.sort_order}. {c.title}</strong><div style={{fontSize:11,color:'var(--text-muted)',marginTop:3}}>Play chapter</div></button>)}</div>}return <div><div style={{marginBottom:24}}><h1 style={{fontSize:'2rem',fontWeight:800}}>Bookshelf</h1><p style={{color:'var(--text-muted)',fontSize:13}}>Your audiobook collection</p></div><div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:8,marginBottom:28}}>{[['Available',summary.available],['Started',summary.in_progress],['Finished',summary.finished],['Favorites',summary.favorites]].map(([l,v])=><div className="card-premium" style={{padding:10,textAlign:'center'}} key={String(l)}><strong style={{display:'block',fontSize:23}}>{v}</strong><span style={{color:'var(--text-muted)',fontSize:9}}>{l}</span></div>)}</div><p className="section-label">All Books</p>{books.map(b=><button onClick={()=>void getAudiobook(b.id).then(setDetail)} className="card-premium" style={{padding:16,marginBottom:10,width:'100%',textAlign:'left',color:'var(--text-primary)'}} key={b.id}><strong>{b.title}</strong><div style={{color:'var(--text-muted)',fontSize:12}}>{b.author} · {b.status.replace('_',' ')}</div></button>)}</div>}




