import { useEffect, useState } from 'react'
import { getAudiobookSummary,getLibrarySummary,getStationQueue,scanAudiobooks,scanMusic,type AudiobookSummary,type LibrarySummary } from '../api'
import { usePlayback } from '../state/PlaybackContext'
import { trackToNowPlaying } from '../utils/mediaMappers'
const empty:AudiobookSummary={available:0,not_started:0,in_progress:0,finished:0,favorites:0,total_listening_seconds:0};
export default function HomePage(){const [library,setLibrary]=useState<LibrarySummary>({tracks:0,artists:0,albums:0}),[books,setBooks]=useState(empty),[scanning,setScanning]=useState(false);const {playQueue}=usePlayback();const load=()=>void Promise.all([getLibrarySummary(),getAudiobookSummary()]).then(([l,b])=>{setLibrary(l);setBooks(b)});useEffect(load,[]);const play=async()=>playQueue((await getStationQueue('recently_added')).queue.map(t=>trackToNowPlaying(t)));const scan=async()=>{setScanning(true);try{await Promise.all([scanMusic(),scanAudiobooks()]);load()}finally{setScanning(false)}};return <div><div className="page-title-centered" style={{marginBottom:24}}><p className="section-label centered-section-label">Your personal library</p><h1 style={{marginBottom:6}}>BM Radio</h1><p style={{color:'var(--text-muted)',fontSize:13}}>Private radio from your NAS library.</p></div><section className="card-premium centered-hero-card" style={{padding:24,marginBottom:28,background:'var(--gradient-radio)'}}><p style={{fontSize:12,opacity:.78,marginBottom:8}}>PRIVATE RADIO</p><h2 style={{fontSize:24,marginBottom:8}}>Start BM Radio</h2><p style={{marginBottom:18,color:'rgba(255,255,255,.82)'}}>Play a fresh queue from your library.</p><button onClick={()=>void play()} style={{padding:'11px 16px',borderRadius:22,background:'#fff',color:'#392973',fontWeight:800}}>Play Recently Added</button></section><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><p className="section-label">Library at a glance</p><button onClick={()=>void scan()} disabled={scanning} style={{fontSize:11,color:'var(--accent-primary)'}}>{scanning?'Scanning...':'Rescan'}</button></div><div style={{display:'grid',gridTemplateColumns:'repeat(2,1fr)',gap:10}}>{[['Tracks',library.tracks],['Artists',library.artists],['Albums',library.albums],['Books',books.available],['In progress',books.in_progress]].map(([label,value])=><div className="card-premium" style={{padding:16}} key={String(label)}><strong style={{display:'block',fontSize:27}}>{value}</strong><span style={{fontSize:11,color:'var(--text-muted)'}}>{label}</span></div>)}</div></div>}




