import { useEffect,useState,type ReactNode } from 'react'
import Artwork from '../components/Artwork'
import LoadingSkeleton from '../components/LoadingSkeleton'
import PageError from '../components/PageError'
import { getAlbumTracks,getAlbums,getArtistQueue,getArtists,getLibrarySummary,getStationQueue,getTracksPage,mediaUrl,searchAll,type AlbumSummary,type ArtistSummary,type LibrarySummary,type SearchResults,type Track } from '../api'
import { usePlayback } from '../state/PlaybackContext'
import { trackToNowPlaying } from '../utils/mediaMappers'

type Tab='Albums'|'Artists'|'Songs'|'Search'
const SearchIcon=()=> <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.2"><circle cx="11" cy="11" r="6"/><path d="m16 16 4 4"/></svg>
const emptySearch:SearchResults={artists:[],albums:[],tracks:[],stations:[],audiobooks:[]}

export default function LibraryPage({onOpenAlbum,onOpenArtist,onOpenBook}:{onOpenAlbum:(a:AlbumSummary)=>void;onOpenArtist:(a:ArtistSummary)=>void;onOpenBook?:(id:number)=>void}){
  const [tab,setTab]=useState<Tab>('Albums'),[summary,setSummary]=useState<LibrarySummary>({tracks:0,artists:0,albums:0}),[albums,setAlbums]=useState<AlbumSummary[]>([]),[artists,setArtists]=useState<ArtistSummary[]>([]),[tracks,setTracks]=useState<Track[]>([]),[songsOffset,setSongsOffset]=useState(0),[songsMore,setSongsMore]=useState(false),[query,setQuery]=useState(''),[search,setSearch]=useState<SearchResults>(emptySearch),[loading,setLoading]=useState(true),[pageError,setPageError]=useState<string|null>(null)
  const {playQueue}=usePlayback()
  const loadAll=()=>{setLoading(true);setPageError(null);Promise.all([getLibrarySummary(),getAlbums(),getArtists(),getTracksPage(100,0)]).then(([s,a,ar,t])=>{setSummary(s);setAlbums(a);setArtists(ar);setTracks(t.items);setSongsOffset(t.items.length);setSongsMore(t.has_more)}).catch(()=>setPageError('Could not load your library. Check your NAS connection.')).finally(()=>setLoading(false))}
  useEffect(loadAll,[])
  if(loading)return <LoadingSkeleton rows={7}/>
  if(pageError)return <PageError message={pageError} onRetry={loadAll}/>
  const play=(list:Track[],index=0)=>playQueue(list.map(t=>trackToNowPlaying(t)),index)
  const playArtist=(artist:string)=>void getArtistQueue(artist).then(r=>play(r.queue))
  const playStation=(type:string,seed?:string|null)=>void getStationQueue(type,seed).then(r=>play(r.queue))
  const loadMoreSongs=()=>void getTracksPage(100,songsOffset).then(p=>{setTracks([...tracks,...p.items]);setSongsOffset(songsOffset+p.items.length);setSongsMore(p.has_more)});const results=async()=>{if(query.trim())setSearch(await searchAll(query.trim()));else setSearch(emptySearch)}
  const tabs:Tab[]=['Albums','Artists','Songs','Search']
  return <div style={{width:'100%',minWidth:0}}><div style={{marginBottom:20}}><h1 style={{fontSize:'2rem',fontWeight:800,letterSpacing:'-0.03em',marginBottom:4}}>Library</h1><p style={{fontSize:13,color:'var(--text-muted)'}}>{summary.tracks} tracks {'\u00b7'} {summary.artists} artists {'\u00b7'} {summary.albums} albums</p></div><div className="library-tabs">{tabs.map(x=><button key={x} aria-label={x} title={x} onClick={()=>setTab(x)} style={{padding:'8px 13px',borderRadius:'var(--radius-pill)',background:tab===x?'var(--accent-primary)':'var(--bg-surface)',whiteSpace:'nowrap',color:tab===x?'#fff':'var(--text-secondary)',display:'grid',placeItems:'center'}}>{x}</button>)}</div>{tab==='Albums'&&<div style={{display:'grid',gap:10}}>{albums.map(a=><AlbumRow key={a.artist+a.title} album={a} onOpen={onOpenAlbum} onPlay={()=>void getAlbumTracks(a.artist,a.title).then(x=>play(x))}/>)}</div>}{tab==='Artists'&&<ArtistList artists={artists} onOpenArtist={onOpenArtist} onPlayArtist={playArtist}/>} {tab==='Songs'&&<div><TrackList tracks={tracks} onPlay={play}/>{songsMore&&<button onClick={loadMoreSongs} className="card-premium" style={{width:'100%',padding:14,marginTop:10,color:'var(--accent-primary)',fontWeight:800}}>Load More Songs</button>}</div>} {tab==='Search'&&<div><div style={{position:'relative',maxWidth:360,margin:'0 auto 14px'}}>{!query&&<span style={{position:'absolute',left:'50%',top:'50%',transform:'translate(-50%,-50%)',color:'var(--text-muted)',display:'flex',gap:8,alignItems:'center',pointerEvents:'none',fontSize:14}}><SearchIcon/>Search music</span>}<input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&void results()} placeholder="" aria-label="Search music" style={{width:'100%',boxSizing:'border-box',padding:'11px 14px',borderRadius:'var(--radius-pill)',border:'1px solid var(--border-subtle)',background:'var(--bg-surface)',color:'var(--text-primary)',textAlign:'center'}}/></div><GroupedSearch search={search} onArtist={onOpenArtist} onAlbum={onOpenAlbum} onPlay={play} onStation={playStation} onBook={onOpenBook}/></div>}</div>
}

function ArtistList({artists,onOpenArtist,onPlayArtist}:{artists:ArtistSummary[];onOpenArtist:(a:ArtistSummary)=>void;onPlayArtist:(name:string)=>void}){return <div style={{display:'grid',gap:8}}>{artists.map(a=><div key={a.name} className="card-premium" style={{padding:'14px 16px',color:'var(--text-primary)',display:'flex',alignItems:'center',gap:12}}><button onClick={()=>onOpenArtist(a)} style={{display:'flex',alignItems:'center',gap:12,flex:1,minWidth:0,textAlign:'left'}}><div style={{width:42,height:42,flexShrink:0,borderRadius:'50%',background:'var(--gradient-radio)',display:'grid',placeItems:'center',fontSize:15,fontWeight:800,color:'rgba(255,255,255,0.9)'}}>{a.name.trim().split(/\s+/).filter(Boolean).slice(0,1).map(w=>w[0]).join('').toUpperCase()||'A'}</div><div style={{flex:1,minWidth:0}}><div style={{fontWeight:600,fontSize:14,whiteSpace:'nowrap',overflow:'hidden',textOverflow:'ellipsis'}}>{a.name}</div><div style={{fontSize:12,color:'var(--text-muted)',marginTop:2}}>{a.track_count} {a.track_count===1?'track':'tracks'}</div></div></button><button onClick={()=>onPlayArtist(a.name)} style={{fontSize:12,color:'var(--accent-primary)',fontWeight:700,flexShrink:0}}>Radio</button></div>)}</div>}
function AlbumRow({album,onOpen,onPlay}:{album:AlbumSummary;onOpen:(a:AlbumSummary)=>void;onPlay:()=>void}){const cover=mediaUrl('/api/media/albums/cover?artist='+encodeURIComponent(album.artist)+'&album='+encodeURIComponent(album.title));return <div className="card-premium" style={{padding:'10px 14px',display:'flex',alignItems:'center',gap:12}}><button onClick={()=>onOpen(album)} style={{display:'flex',alignItems:'center',gap:12,flex:1,minWidth:0,textAlign:'left'}}><Artwork src={cover} label={album.title} size={52}/><div style={{flex:1,minWidth:0}}><div style={{fontWeight:600,fontSize:14,whiteSpace:'nowrap',overflow:'hidden',textOverflow:'ellipsis',marginBottom:2}}>{album.title}</div><div style={{fontSize:12,color:'var(--text-muted)'}}>{album.artist} {'\u00b7'} {album.track_count} {album.track_count===1?'track':'tracks'}</div></div></button><button onClick={onPlay} style={{padding:'9px 14px',borderRadius:'var(--radius-pill)',background:'var(--accent-primary)',color:'#fff',fontWeight:700,fontSize:13,flexShrink:0}}>Play</button></div>}
function Section({title,children}:{title:string;children:ReactNode}){return <section style={{marginBottom:18}}><p className="section-label">{title}</p><div style={{display:'grid',gap:7}}>{children}</div></section>}
function GroupedSearch({search,onArtist,onAlbum,onPlay,onStation,onBook}:{search:SearchResults;onArtist:(a:ArtistSummary)=>void;onAlbum:(a:AlbumSummary)=>void;onPlay:(x:Track[],i?:number)=>void;onStation:(type:string,seed?:string|null)=>void;onBook?:(id:number)=>void}){const has=search.artists.length||search.albums.length||search.tracks.length||search.stations.length||search.audiobooks.length;if(!has)return <div className="card-premium" style={{padding:22,textAlign:'center',color:'var(--text-muted)'}}>Type a search and press Enter.</div>;return <div>{!!search.artists.length&&<Section title="Artists">{search.artists.map(a=><button className="card-premium" style={{padding:12,textAlign:'left'}} key={a.name} onClick={()=>onArtist(a)}><strong>{a.name}</strong><span style={{display:'block',fontSize:12,color:'var(--text-muted)'}}>{a.track_count} tracks</span></button>)}</Section>}{!!search.albums.length&&<Section title="Albums">{search.albums.map(a=><AlbumRow key={a.artist+a.title} album={a} onOpen={onAlbum} onPlay={()=>{}}/>)}</Section>}{!!search.tracks.length&&<Section title="Songs"><TrackList tracks={search.tracks} onPlay={onPlay}/></Section>}{!!search.stations.length&&<Section title="Stations">{search.stations.map(s=><button className="card-premium" style={{padding:12,textAlign:'left'}} key={s.name} onClick={()=>onStation(s.type,s.seed_value)}><strong>{s.name}</strong><span style={{display:'block',fontSize:12,color:'var(--text-muted)'}}>{s.track_count} tracks</span></button>)}</Section>}{!!search.audiobooks.length&&<Section title="Books">{search.audiobooks.map(b=><button className="card-premium" style={{padding:12,textAlign:'left'}} key={b.id} onClick={()=>onBook?.(b.id)}><strong>{b.title}</strong><span style={{display:'block',fontSize:12,color:'var(--text-muted)'}}>{b.author}</span></button>)}</Section>}</div>}
function TrackList({tracks,onPlay}:{tracks:Track[];onPlay:(x:Track[],i?:number)=>void}){return <div style={{display:'grid',gap:7}}>{tracks.map((t,i)=><button key={String(t.id)+'-'+i+'-'+t.title+'-'+t.album} onClick={()=>onPlay(tracks,i)} className="card-premium" style={{padding:12,textAlign:'left'}}><strong style={{display:'block',fontSize:14,fontWeight:600,marginBottom:2}}>{t.title}</strong><span style={{display:'block',fontSize:12,color:'var(--text-muted)'}}>{t.artist}{t.album?' \u00b7 '+t.album:''}</span></button>)}</div>}