import { useEffect, useState, type ReactNode } from 'react'
import Artwork from '../components/Artwork'
import LoadingSkeleton from '../components/LoadingSkeleton'
import PageError from '../components/PageError'
import TrackActionSheet from '../components/TrackActionSheet'
import useLongPress from '../hooks/useLongPress'
import { createPlaylist, deletePlaylist, getAlbumTracks, getAlbumsPage, getArtistsPage, getLibrarySummary, peekCache, getPlaylistQueue, getPlaylists, getSmartPlaylistQueue, getSmartPlaylists, getStationQueue, getTracksPage, mediaUrl, searchAll, type AlbumPage, type AlbumSummary, type ArtistPage, type ArtistSummary, type LibrarySummary, type PlaylistSummary, type SmartPlaylistSummary, type SearchResults, type Track } from '../api'
import { useRadioActions } from '../hooks/useRadioActions'
import { usePlayback, type QueueSource } from '../state/PlaybackContext'
import { trackToNowPlaying } from '../utils/mediaMappers'
import { cleanTrackTitle } from '../utils/displayText'

type Tab = 'Albums' | 'Artists' | 'Songs' | 'Search' | 'Playlists'
const SearchIcon = () => <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.2"><circle cx="11" cy="11" r="6"/><path d="m16 16 4 4"/></svg>
const emptySearch: SearchResults = { artists: [], albums: [], tracks: [], stations: [], audiobooks: [] }

export default function LibraryPage({ onOpenAlbum, onOpenArtist, onOpenBook, onOpenPlaylist, onOpenIntegrity }: { onOpenAlbum: (a: AlbumSummary) => void; onOpenArtist: (a: ArtistSummary) => void; onOpenBook?: (id: number) => void; onOpenPlaylist?: (id: number) => void; onOpenIntegrity?: () => void }) {
  const cachedSummary = peekCache<LibrarySummary>('library-summary')
  const cachedAlbums = peekCache<AlbumPage>('albums-page:100:0')
  const cachedArtists = peekCache<ArtistPage>('artists-page:100:0')
  const [tab, setTab] = useState<Tab>('Albums')
  const [summary, setSummary] = useState<LibrarySummary>(cachedSummary ?? { tracks: 0, artists: 0, albums: 0 })
  const [albums, setAlbums] = useState<AlbumSummary[]>(cachedAlbums?.items ?? [])
  const [artists, setArtists] = useState<ArtistSummary[]>(cachedArtists?.items ?? [])
  const [tracks, setTracks] = useState<Track[]>([])
  const [playlists, setPlaylists] = useState<PlaylistSummary[]>([])
  const [smart, setSmart] = useState<SmartPlaylistSummary[]>([])
  const [songsOffset, setSongsOffset] = useState(0)
  const [songsMore, setSongsMore] = useState(false)
  const [query, setQuery] = useState('')
  const [search, setSearch] = useState<SearchResults>(emptySearch)
  const [loading, setLoading] = useState(!cachedSummary || !cachedAlbums)
  const [pageError, setPageError] = useState<string | null>(null)
  const [actionTrack, setActionTrack] = useState<Track | null>(null)
  const { playQueue } = usePlayback()
  const { startSongRadio, saveSongStation, startArtistRadio } = useRadioActions()

  const play = (list: Track[], index = 0, source?: QueueSource) => playQueue(list.map(track => trackToNowPlaying(track)), index, source)
  const loadAll = () => {
    if (!albums.length) setLoading(true)
    setPageError(null)
    Promise.all([getLibrarySummary(), getAlbumsPage(100, 0)])
      .then(([s, a]) => { setSummary(s); setAlbums(a.items) })
      .catch(() => { if (!albums.length) setPageError('Could not load your library. Check your NAS connection.') })
      .finally(() => setLoading(false))
  }
  useEffect(loadAll, [])
  useEffect(() => {
    if (tab === 'Artists' && !artists.length) void getArtistsPage(100, 0).then(p => setArtists(p.items)).catch(() => setPageError('Could not load artists.'))
    if (tab === 'Songs' && !tracks.length) void getTracksPage(100, 0).then(t => { setTracks(t.items); setSongsOffset(t.items.length); setSongsMore(t.has_more) }).catch(() => setPageError('Could not load songs.'))
    if (tab === 'Playlists' && !playlists.length && !smart.length) void Promise.all([getPlaylists(), getSmartPlaylists()]).then(([p, sp]) => { setPlaylists(p); setSmart(sp) }).catch(() => setPageError('Could not load playlists.'))
  }, [tab])

  if (loading) return <LoadingSkeleton rows={7} preserveSpace />
  if (pageError) return <PageError message={pageError} onRetry={loadAll} />

  const playArtist = (artist: string) => startArtistRadio(artist)
  const playStation = (type: string, seed?: string | null, stationName?: string) => void getStationQueue(type, seed).then(r => {
    const name = stationName ?? seed ?? type
    playQueue(r.queue.map(t => trackToNowPlaying(t, { stationName: name })), 0, { kind: 'station', stationType: type, seedValue: seed, stationName: name, canContinue: true } satisfies QueueSource)
  })
  const loadMoreSongs = () => void getTracksPage(100, songsOffset).then(p => { setTracks([...tracks, ...p.items]); setSongsOffset(songsOffset + p.items.length); setSongsMore(p.has_more) })
  const results = async () => { if (query.trim()) setSearch(await searchAll(query.trim())); else setSearch(emptySearch) }
  const refreshPlaylists = () => void Promise.all([getPlaylists(), getSmartPlaylists()]).then(([p, sp]) => { setPlaylists(p); setSmart(sp) })
  const openAlbumForTrack = (track: Track) => track.album && onOpenAlbum({ title: track.album, artist: track.artist, track_count: 0 })
  const tabs: Tab[] = ['Albums', 'Artists', 'Songs', 'Search', 'Playlists']

  return (
    <div style={{ width: '100%', minWidth: 0 }}>
      <div style={{ marginBottom: 20, display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: 12 }}><div><h1 style={{ fontSize: '1.6rem', fontWeight: 800, letterSpacing: '-0.03em', marginBottom: 3 }}>Library</h1><p style={{ fontSize: 12, color: 'var(--text-muted)' }}>{summary.tracks} tracks {'\u00b7'} {summary.artists} artists {'\u00b7'} {summary.albums} albums</p></div>{onOpenIntegrity && <button onClick={onOpenIntegrity} style={{ padding: '8px 10px', borderRadius: 'var(--radius-pill)', background: 'var(--bg-surface)', border: '1px solid var(--border-subtle)', color: 'var(--text-secondary)', fontSize: 12, fontWeight: 700 }}>Integrity</button>}</div>
      <div className="library-tabs">{tabs.map(x => <button key={x} aria-label={x} title={x} onClick={() => setTab(x)} style={{ padding: '8px 11px', borderRadius: 'var(--radius-pill)', background: tab === x ? 'var(--accent-primary)' : 'var(--bg-surface)', whiteSpace: 'nowrap', color: tab === x ? '#fff' : 'var(--text-secondary)', display: 'grid', placeItems: 'center', fontSize: 13, fontWeight: tab === x ? 600 : 400, flexShrink: 0, border: '1px solid', borderColor: tab === x ? 'transparent' : 'var(--border-subtle)' }}>{x}</button>)}</div>
      <div className="tab-content-fade" key={tab}>
        {tab === 'Albums' && <div style={{ display: 'grid', gap: 10 }}>{albums.map(a => <AlbumRow key={a.artist + a.title} album={a} onOpen={onOpenAlbum} onPlay={() => void getAlbumTracks(a.artist, a.title).then(x => play(x, 0, { kind: 'album', artist: a.artist, album: a.title, canContinue: false }))} />)}</div>}
        {tab === 'Artists' && (artists.length ? <ArtistList artists={artists} onOpenArtist={onOpenArtist} onPlayArtist={playArtist} /> : <LoadingSkeleton rows={5} compact preserveSpace />)}
        {tab === 'Songs' && <div>{tracks.length ? <TrackList tracks={tracks} onPlay={play} onAction={setActionTrack} /> : <LoadingSkeleton rows={6} compact preserveSpace />}{songsMore && <button onClick={loadMoreSongs} className="card-premium" style={{ width: '100%', padding: 14, marginTop: 10, color: 'var(--accent-primary)', fontWeight: 800 }}>Load More Songs</button>}</div>}
        {tab === 'Search' && <div><div style={{ position: 'relative', marginBottom: 16 }}><span style={{ position: 'absolute', left: 14, top: '50%', transform: 'translateY(-50%)', color: 'var(--text-muted)', pointerEvents: 'none', display: 'flex', alignItems: 'center' }}><SearchIcon /></span><input value={query} onChange={e => setQuery(e.target.value)} onKeyDown={e => e.key === 'Enter' && void results()} placeholder="Search music, albums, artists..." aria-label="Search music" style={{ width: '100%', boxSizing: 'border-box', padding: '13px 42px', borderRadius: 'var(--radius-m)', border: '1px solid var(--border-subtle)', background: 'var(--bg-card)', color: 'var(--text-primary)', fontSize: 14, outline: 'none' }} onFocus={e => (e.currentTarget.style.borderColor = 'var(--accent-primary)')} onBlur={e => (e.currentTarget.style.borderColor = 'var(--border-subtle)')} />{query && <button onClick={() => { setQuery(''); setSearch(emptySearch) }} style={{ position: 'absolute', right: 12, top: '50%', transform: 'translateY(-50%)', width: 22, height: 22, borderRadius: '50%', background: 'var(--bg-surface)', color: 'var(--text-muted)', fontSize: 14, display: 'grid', placeItems: 'center' }} aria-label="Clear search">&times;</button>}</div>{!query && <div style={{ textAlign: 'center', paddingTop: 32, paddingBottom: 16 }}><div style={{ width: 56, height: 56, borderRadius: '50%', background: 'var(--accent-primary-dim)', border: '1px solid rgba(139,109,255,0.2)', display: 'grid', placeItems: 'center', margin: '0 auto 14px', color: 'var(--accent-primary)' }}><SearchIcon /></div><p style={{ fontSize: 14, fontWeight: 600, color: 'var(--text-secondary)', marginBottom: 6 }}>Search your library</p><p style={{ fontSize: 12, color: 'var(--text-muted)', lineHeight: 1.5 }}>Find songs, albums, artists, stations,<br />and audiobooks.</p></div>}{query && <GroupedSearch search={search} onArtist={onOpenArtist} onAlbum={onOpenAlbum} onPlay={play} onStation={playStation} onBook={onOpenBook} onAction={setActionTrack} />}</div>}
        {tab === 'Playlists' && (playlists.length || smart.length ? <PlaylistsTab playlists={playlists} smart={smart} onRefresh={refreshPlaylists} onOpen={id => onOpenPlaylist?.(id)} onPlay={(id, shuffle) => void getPlaylistQueue(id, shuffle).then(r => play(r.queue, 0, { kind: 'playlist', playlistId: id, canContinue: false }))} onSmart={(key, shuffle) => void getSmartPlaylistQueue(key, shuffle).then(r => play(r.queue, 0, { kind: 'smart-playlist', key, canContinue: false }))} /> : <LoadingSkeleton rows={5} compact preserveSpace />)}
      </div>
      <TrackActionSheet open={!!actionTrack} track={actionTrack} onClose={() => setActionTrack(null)} onGoToAlbum={openAlbumForTrack} onGoToArtist={track => onOpenArtist({ name: track.artist, track_count: 0 })} onStartRadio={startSongRadio} onSaveStation={saveSongStation} />
    </div>
  )
}

function ArtistList({ artists, onOpenArtist, onPlayArtist }: { artists: ArtistSummary[]; onOpenArtist: (a: ArtistSummary) => void; onPlayArtist: (name: string) => void }) { return <div style={{ display: 'grid', gap: 8 }}>{artists.map(a => <div key={a.name} className="card-premium" style={{ padding: '14px 16px', color: 'var(--text-primary)', display: 'flex', alignItems: 'center', gap: 12 }}><button onClick={() => onOpenArtist(a)} style={{ display: 'flex', alignItems: 'center', gap: 12, flex: 1, minWidth: 0, textAlign: 'left' }}><div style={{ width: 42, height: 42, flexShrink: 0, borderRadius: '50%', background: 'var(--gradient-radio)', display: 'grid', placeItems: 'center', fontSize: 15, fontWeight: 800, color: 'rgba(255,255,255,0.9)' }}>{a.name.trim().split(/\s+/).filter(Boolean).slice(0, 1).map(w => w[0]).join('').toUpperCase() || 'A'}</div><div style={{ flex: 1, minWidth: 0 }}><div style={{ fontWeight: 600, fontSize: 14, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{a.name}</div><div style={{ fontSize: 12, color: 'var(--text-muted)', marginTop: 2 }}>{a.track_count} {a.track_count === 1 ? 'track' : 'tracks'}</div></div></button><button onClick={() => onPlayArtist(a.name)} style={{ fontSize: 12, color: 'var(--accent-primary)', fontWeight: 700, flexShrink: 0 }}>Radio</button></div>)}</div> }
function AlbumRow({ album, onOpen, onPlay }: { album: AlbumSummary; onOpen: (a: AlbumSummary) => void; onPlay: () => void }) { const cover = mediaUrl('/api/media/albums/cover?artist=' + encodeURIComponent(album.artist) + '&album=' + encodeURIComponent(album.title)); return <div className="card-premium" style={{ padding: '10px 14px', display: 'flex', alignItems: 'center', gap: 12 }}><button onClick={() => onOpen(album)} style={{ display: 'flex', alignItems: 'center', gap: 12, flex: 1, minWidth: 0, textAlign: 'left' }}><Artwork src={cover} label={album.title} size={52} /><div style={{ flex: 1, minWidth: 0 }}><div style={{ fontWeight: 600, fontSize: 14, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis', marginBottom: 2 }}>{album.title}</div><div style={{ fontSize: 12, color: 'var(--text-muted)' }}>{album.artist} {'\u00b7'} {album.track_count} {album.track_count === 1 ? 'track' : 'tracks'}</div></div></button><button onClick={onPlay} style={{ padding: '9px 14px', borderRadius: 'var(--radius-pill)', background: 'var(--accent-primary)', color: '#fff', fontWeight: 700, fontSize: 13, flexShrink: 0 }}>Play</button></div> }
function Section({ title, children }: { title: string; children: ReactNode }) { return <section style={{ marginBottom: 18 }}><p className="section-label">{title}</p><div style={{ display: 'grid', gap: 7 }}>{children}</div></section> }
function GroupedSearch({ search, onArtist, onAlbum, onPlay, onStation, onBook, onAction }: { search: SearchResults; onArtist: (a: ArtistSummary) => void; onAlbum: (a: AlbumSummary) => void; onPlay: (x: Track[], i?: number) => void; onStation: (type: string, seed?: string | null, stationName?: string) => void; onBook?: (id: number) => void; onAction: (track: Track) => void }) { const has = search.artists.length || search.albums.length || search.tracks.length || search.stations.length || search.audiobooks.length; if (!has) return <div className="card-premium" style={{ padding: 22, textAlign: 'center', color: 'var(--text-muted)' }}>Type a search and press Enter.</div>; return <div>{!!search.artists.length && <Section title="Artists">{search.artists.map(a => <button className="card-premium" style={{ padding: 12, textAlign: 'left' }} key={a.name} onClick={() => onArtist(a)}><strong>{a.name}</strong><span style={{ display: 'block', fontSize: 12, color: 'var(--text-muted)' }}>{a.track_count} tracks</span></button>)}</Section>}{!!search.albums.length && <Section title="Albums">{search.albums.map(a => <AlbumRow key={a.artist + a.title} album={a} onOpen={onAlbum} onPlay={() => {}} />)}</Section>}{!!search.tracks.length && <Section title="Songs"><TrackList tracks={search.tracks} onPlay={onPlay} onAction={onAction} /></Section>}{!!search.stations.length && <Section title="Stations">{search.stations.map(s => <button className="card-premium" style={{ padding: 12, textAlign: 'left' }} key={s.name} onClick={() => onStation(s.type, s.seed_value, s.name)}><strong>{s.name}</strong><span style={{ display: 'block', fontSize: 12, color: 'var(--text-muted)' }}>{s.track_count} tracks</span></button>)}</Section>}{!!search.audiobooks.length && <Section title="Books">{search.audiobooks.map(b => <button className="card-premium" style={{ padding: 12, textAlign: 'left' }} key={b.id} onClick={() => onBook?.(b.id)}><strong>{b.title}</strong><span style={{ display: 'block', fontSize: 12, color: 'var(--text-muted)' }}>{b.author}</span></button>)}</Section>}</div> }
function TrackList({ tracks, onPlay, onAction }: { tracks: Track[]; onPlay: (x: Track[], i?: number) => void; onAction: (track: Track) => void }) { return <div style={{ display: 'grid', gap: 7 }}>{tracks.map((t, i) => <TrackRow key={String(t.id) + '-' + i + '-' + t.title + '-' + t.album} track={t} onPlay={() => onPlay(tracks, i)} onAction={() => onAction(t)} />)}</div> }
function TrackRow({ track, onPlay, onAction }: { track: Track; onPlay: () => void; onAction: () => void }) { const longPress = useLongPress(onAction); return <div className="card-premium" style={{ padding: 12, display: 'flex', alignItems: 'center', gap: 8 }} {...longPress}><button onClick={onPlay} style={{ flex: 1, minWidth: 0, textAlign: 'left' }}><strong style={{ display: 'block', fontSize: 14, fontWeight: 600, marginBottom: 2, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{cleanTrackTitle(track.title)}</strong><span style={{ display: 'block', fontSize: 12, color: 'var(--text-muted)', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{track.artist}{track.album ? ' \u00b7 ' + track.album : ''}</span></button><button className="track-overflow-button" aria-label="Track actions" onClick={(event) => { event.stopPropagation(); onAction() }}>&#8943;</button></div> }

function PlaylistsTab({ playlists, smart, onRefresh, onOpen, onPlay, onSmart }: { playlists: PlaylistSummary[]; smart: SmartPlaylistSummary[]; onRefresh: () => void; onOpen: (id: number) => void; onPlay: (id: number, shuffle?: boolean) => void; onSmart: (key: string, shuffle?: boolean) => void }) {
  const [showCreate, setShowCreate] = useState(false)
  const [name, setName] = useState('')
  const [busy, setBusy] = useState(false)
  const [deleteConfirm, setDeleteConfirm] = useState<number | null>(null)
  const create = async () => { const value = name.trim(); if (!value) return; setBusy(true); try { await createPlaylist(value); setName(''); setShowCreate(false); onRefresh() } finally { setBusy(false) } }
  const confirmDelete = async (id: number) => { await deletePlaylist(id); setDeleteConfirm(null); onRefresh() }
  return <div>
    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10 }}><p className="section-label" style={{ margin: 0 }}>My Playlists</p><button onClick={() => setShowCreate(true)} style={{ width: 32, height: 32, borderRadius: '50%', background: 'var(--accent-primary)', display: 'grid', placeItems: 'center', color: '#fff', fontSize: 20, fontWeight: 300, boxShadow: '0 2px 10px var(--accent-primary-glow)' }} aria-label="Create playlist">+</button></div>
    {!playlists.length ? <div className="card-premium" style={{ padding: '22px 18px', textAlign: 'center', marginBottom: 24 }}><p style={{ fontSize: 14, color: 'var(--text-secondary)', marginBottom: 6 }}>No playlists yet</p><p style={{ fontSize: 12, color: 'var(--text-muted)' }}>Tap <strong style={{ color: 'var(--accent-primary)' }}>+</strong> above to create one.</p></div> : <div style={{ display: 'grid', gap: 9, marginBottom: 24 }}>{playlists.map(p => <div className="card-premium" style={{ padding: 14, display: 'flex', alignItems: 'center', gap: 12 }} key={p.id}><button onClick={() => onOpen(p.id)} style={{ flex: 1, minWidth: 0, textAlign: 'left' }}><strong style={{ display: 'block' }}>{p.name}</strong><span style={{ fontSize: 12, color: 'var(--text-muted)' }}>{p.track_count} {p.track_count === 1 ? 'track' : 'tracks'}</span></button><button onClick={() => onPlay(p.id, false)} style={{ fontSize: 12, color: 'var(--accent-primary)', fontWeight: 800, flexShrink: 0 }}>Play</button><button onClick={() => onPlay(p.id, true)} style={{ fontSize: 12, color: 'var(--text-muted)', fontWeight: 800, flexShrink: 0 }}>Shuffle</button>{deleteConfirm === p.id ? <div style={{ display: 'flex', gap: 6, flexShrink: 0 }}><button onClick={() => void confirmDelete(p.id)} style={{ fontSize: 11, color: '#ff6b6b', fontWeight: 700 }}>Delete</button><button onClick={() => setDeleteConfirm(null)} style={{ fontSize: 11, color: 'var(--text-muted)' }}>Cancel</button></div> : <button onClick={() => setDeleteConfirm(p.id)} style={{ width: 28, height: 28, flexShrink: 0, display: 'grid', placeItems: 'center', color: 'var(--text-muted)', fontSize: 18, borderRadius: '50%' }} aria-label="Delete playlist">&times;</button>}</div>)}</div>}
    <p className="section-label" style={{ marginBottom: 10 }}>Smart Collections</p>
    <div style={{ display: 'grid', gap: 9, marginBottom: 20 }}>{smart.map(p => <div className="card-premium" style={{ padding: 14, display: 'flex', alignItems: 'center', gap: 12 }} key={p.id}><div style={{ flex: 1, minWidth: 0 }}><strong style={{ display: 'block' }}>{p.name}</strong><span style={{ display: 'block', fontSize: 12, color: 'var(--text-muted)' }}>{p.description} {'\u00b7'} {p.track_count} {p.track_count === 1 ? 'track' : 'tracks'}</span></div><button onClick={() => onSmart(String(p.id), false)} style={{ fontSize: 12, color: 'var(--accent-primary)', fontWeight: 800 }}>Play</button><button onClick={() => onSmart(String(p.id), true)} style={{ fontSize: 12, color: 'var(--text-muted)', fontWeight: 800 }}>Shuffle</button></div>)}</div>
    {showCreate && <div style={{ position: 'fixed', inset: 0, zIndex: 200, background: 'rgba(0,0,0,0.65)', display: 'flex', alignItems: 'flex-end' }} onClick={() => setShowCreate(false)}><div style={{ width: '100%', background: 'var(--bg-card)', border: '1px solid var(--border-subtle)', borderRadius: '24px 24px 0 0', padding: '24px 20px 36px', boxShadow: '0 -8px 40px rgba(0,0,0,0.5)' }} onClick={e => e.stopPropagation()}><div style={{ width: 40, height: 4, borderRadius: 2, background: 'var(--border-subtle)', margin: '0 auto 20px' }} /><h2 style={{ fontSize: '1.2rem', fontWeight: 800, letterSpacing: '-0.02em', marginBottom: 20 }}>Create Playlist</h2><input value={name} onChange={e => setName(e.target.value)} onKeyDown={e => e.key === 'Enter' && void create()} placeholder="Playlist name" autoFocus style={{ width: '100%', boxSizing: 'border-box', padding: '13px 16px', borderRadius: 'var(--radius-pill)', border: '1px solid var(--border-subtle)', background: 'var(--bg-surface)', color: 'var(--text-primary)', fontSize: 15, marginBottom: 14 }} /><button onClick={() => void create()} disabled={busy || !name.trim()} style={{ width: '100%', padding: '14px', borderRadius: 'var(--radius-pill)', background: name.trim() ? 'var(--gradient-radio)' : 'var(--bg-surface)', color: name.trim() ? '#fff' : 'var(--text-muted)', fontWeight: 800, fontSize: 15 }}>{busy ? 'Creating...' : 'Create'}</button></div></div>}
  </div>
}
