import { useEffect,useState } from 'react'
import Artwork from '../components/Artwork'
import LoadingSkeleton from '../components/LoadingSkeleton'
import PageError from '../components/PageError'
import { getPlaylist,getPlaylistQueue,mediaUrl,removeTrackFromPlaylist,type PlaylistDetail } from '../api'
import { usePlayback } from '../state/PlaybackContext'
import { trackToNowPlaying } from '../utils/mediaMappers'
import { cleanTrackTitle } from '../utils/displayText'
export default function PlaylistDetailPage({playlistId,onBack}:{playlistId:number;onBack:()=>void}){const [detail,setDetail]=useState<PlaylistDetail|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null);const {playQueue}=usePlayback();const load=()=>{setLoading(true);setError(null);getPlaylist(playlistId).then(setDetail).catch(()=>setError('Could not load playlist.')).finally(()=>setLoading(false))};useEffect(load,[playlistId]);if(loading)return <LoadingSkeleton rows={6}/>;if(error||!detail)return <PageError message={error??'Playlist not found.'} onRetry={load}/>;const play=(shuffle=false)=>void getPlaylistQueue(detail.id,shuffle).then(r=>playQueue(r.queue.map(t=>trackToNowPlaying(t))));const remove=(trackId:number)=>void removeTrackFromPlaylist(detail.id,trackId).then(setDetail);return <div><button onClick={onBack} style={{display:'flex',alignItems:'center',gap:6,padding:'10px 0',marginBottom:16,minHeight:44,color:'var(--text-secondary)',fontSize:14,fontWeight:500}}>&larr; Back to Library</button><div className="page-title-centered" style={{marginBottom:22}}><h1>{detail.name}</h1><p>{detail.track_count} {detail.track_count===1?'track':'tracks'}</p>{detail.description&&<p>{detail.description}</p>}<div style={{display:'flex',gap:10,justifyContent:'center',marginTop:14}}><button onClick={()=>play(false)} disabled={!detail.tracks.length} style={{padding:'10px 16px',borderRadius:'var(--radius-pill)',background:'var(--accent-primary)',color:'#fff',fontWeight:800}}>Play</button><button onClick={()=>play(true)} disabled={!detail.tracks.length} style={{padding:'10px 16px',borderRadius:'var(--radius-pill)',background:'var(--bg-surface)',color:'var(--text-primary)',fontWeight:800}}>Shuffle</button></div></div><p className="section-label">Tracks</p>{detail.tracks.map((t,i)=><div className="card-premium" style={{padding:12,display:'flex',gap:12,alignItems:'center',marginBottom:8}} key={`${t.id}-${i}`}><button onClick={()=>playQueue(detail.tracks.map(x=>trackToNowPlaying(x)),i)} style={{display:'flex',gap:12,alignItems:'center',flex:1,minWidth:0,textAlign:'left'}}><Artwork src={mediaUrl(t.cover_url)} label={t.title} size={42}/><span style={{minWidth:0}}><strong style={{display:'block',whiteSpace:'nowrap',overflow:'hidden',textOverflow:'ellipsis'}}>{cleanTrackTitle(t.title)}</strong><span style={{fontSize:12,color:'var(--text-muted)'}}>{t.artist}{t.album?' · '+t.album:''}</span></span></button><button onClick={()=>remove(t.id)} style={{fontSize:12,color:'var(--text-muted)'}}>Remove</button></div>)}{!detail.tracks.length&&<div className="card-premium" style={{padding:22,textAlign:'center',color:'var(--text-muted)'}}>No tracks yet. Add the current song from Now Playing.</div>}</div>}
