import { useEffect,useMemo,useState } from 'react'
import Artwork from '../components/Artwork'
import IconButton from '../components/IconButton'
import LoadingSkeleton from '../components/LoadingSkeleton'
import PageError from '../components/PageError'
import { PlayIcon } from '../components/PlayerIcons'
import { getStationQueue,getStations,type Station } from '../api'
import { usePlayback } from '../state/PlaybackContext'
import { trackToNowPlaying } from '../utils/mediaMappers'
const groups=[['Featured',['recently_added','favorites','deep_cuts']],['Genres',['genre']],['Artists',['artist']]] as const
export default function RadioPage(){const [stations,setStations]=useState<Station[]>([]),[busy,setBusy]=useState<string|null>(null),[loading,setLoading]=useState(true),[pageError,setPageError]=useState<string|null>(null);const {playQueue}=usePlayback();const loadStations=()=>{setLoading(true);setPageError(null);getStations().then(setStations).catch(()=>setPageError('Could not load stations. Check your NAS connection.')).finally(()=>setLoading(false))};useEffect(loadStations,[]);const play=async(s:Station)=>{setBusy(s.name);try{const seed=s.seed_value??((s.type==='genre'||s.type==='artist')?s.name.replace(/ Radio$/,''):null);playQueue((await getStationQueue(s.type,seed)).queue.map(t=>trackToNowPlaying(t,{stationName:s.name})))}finally{setBusy(null)}};const featured=useMemo(()=>stations.find(s=>s.type==='recently_added')??stations[0],[stations]);if(loading)return <LoadingSkeleton rows={6}/>;if(pageError)return <PageError message={pageError} onRetry={loadStations}/>;return <div style={{width:'100%',maxWidth:'100%',minWidth:0,overflowX:'hidden'}}><div style={{marginBottom:22}}><h1 style={{fontSize:'2rem',fontWeight:800,letterSpacing:'-0.03em',marginBottom:4}}>Stations</h1><p style={{color:'var(--text-muted)',fontSize:13}}>Radio made from your library.</p></div>{featured&&<button onClick={()=>void play(featured)} disabled={!!busy} style={{width:'100%',padding:20,borderRadius:'var(--radius-card)',background:'var(--gradient-radio)',textAlign:'center',color:'#fff',marginBottom:28,boxShadow:'var(--shadow-glow)'}}><span style={{fontSize:10,fontWeight:800,letterSpacing:'.12em',opacity:.76}}>FEATURED STATION</span><strong style={{display:'block',fontSize:22,margin:'8px 0 4px'}}>{featured.name}</strong><span style={{fontSize:13,opacity:.82}}>{busy===featured.name?'Loading station...':`${featured.track_count} ${featured.track_count===1?'track':'tracks'} ready to play`}</span></button>}{groups.map(([title,types])=>{const list=stations.filter(s=>types.includes(s.type as never)&&s!==featured);if(!list.length)return null;return <section key={title} style={{marginBottom:26}}><p className="section-label">{title}</p><div style={{display:'grid',gap:9}}>{list.map(s=><div className="card-premium" style={{padding:12,display:'grid',gridTemplateColumns:'48px minmax(0,1fr) 38px',alignItems:'center',gap:12,width:'100%',maxWidth:'100%',minWidth:0,overflow:'hidden'}} key={s.name}><Artwork label={s.name} kind="station" size={48}/><div style={{flex:1,minWidth:0}}><strong style={{display:'block',whiteSpace:'nowrap',overflow:'hidden',textOverflow:'ellipsis'}}>{s.name}</strong><span style={{fontSize:12,color:'var(--text-muted)'}}>{s.track_count} {s.track_count===1?'track':'tracks'}</span></div><IconButton label={'Play '+s.name} onClick={()=>void play(s)} active={busy===s.name} disabled={!!busy&&busy!==s.name} size={38}><PlayIcon/></IconButton></div>)}</div></section>})}</div>}