import React, { useEffect, useState } from 'react'
import BottomNav from './BottomNav'
import MiniPlayer from './MiniPlayer'

const API_BASE = import.meta.env.VITE_API_BASE_URL ?? 'http://127.0.0.1:8094/api'
const MODAL_PAGES = new Set(['nowPlaying', 'queue'])

function BMLogo(){const [failed,setFailed]=useState(false);return <span style={{width:32,height:32,borderRadius:12,display:'grid',placeItems:'center',overflow:'hidden',background:'rgba(139,109,255,.16)',boxShadow:'0 10px 28px rgba(139,109,255,.24)',border:'1px solid var(--border-soft)'}}>{!failed?<img src="/assets/bm-nas-mark.svg" alt="BM" onError={()=>setFailed(true)} style={{width:'100%',height:'100%',objectFit:'contain'}}/>:<strong style={{fontSize:12,letterSpacing:'.06em'}}>BM</strong>}</span>}
function AppBrandBar(){return <div style={{display:'flex',alignItems:'center',justifyContent:'space-between',padding:'14px 16px 10px'}}><div style={{display:'flex',alignItems:'center',gap:8}}><BMLogo/><div><div style={{fontSize:18,fontWeight:800,letterSpacing:'-0.03em',color:'var(--text-primary)',lineHeight:1.1}}>Radio</div><div style={{fontSize:11,fontWeight:400,color:'var(--text-muted)',letterSpacing:'0.01em',lineHeight:1,marginTop:2}}>Personal cloud library. Stream anywhere.</div></div></div><div style={{width:32,height:32}} aria-hidden="true"/></div>}

export default function AppShell({children,currentPage,onPageChange,onOpenNowPlaying,onOpenQueue}:{children:React.ReactNode;currentPage:string;onPageChange:(page:string)=>void;onOpenNowPlaying:()=>void;onOpenQueue?:()=>void}){const isModal=MODAL_PAGES.has(currentPage);const [nasOnline,setNasOnline]=useState(true);useEffect(()=>{const check=()=>{const controller=new AbortController();const timeout=window.setTimeout(()=>controller.abort(),4000);fetch(`${API_BASE}/health`,{signal:controller.signal}).then(()=>setNasOnline(true)).catch(()=>setNasOnline(false)).finally(()=>window.clearTimeout(timeout))};check();const interval=window.setInterval(check,15000);return()=>window.clearInterval(interval)},[]);return <div className="app-shell" data-page={currentPage}>{!nasOnline&&<div style={{background:'rgba(220,60,60,0.12)',borderBottom:'1px solid rgba(220,60,60,0.25)',padding:'7px 16px',fontSize:12,color:'#ff8888',textAlign:'center',fontWeight:500,letterSpacing:'0.01em'}}>NAS unreachable &mdash; check your connection</div>}{!isModal&&<AppBrandBar/>}<main className="app-main" style={{paddingTop:isModal?24:8}}>{children}</main>{!isModal&&<div className="bottom-rail"><MiniPlayer onOpen={onOpenNowPlaying} onOpenQueue={onOpenQueue}/><BottomNav currentPage={currentPage} onPageChange={onPageChange}/></div>}</div>}
