import type { ComponentType } from 'react'
type NavId='home'|'radio'|'library'|'bookshelf'
const HomeIcon=()=> <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="m3 10 9-7 9 7v10a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V10Z"/><path d="M9 21v-7h6v7"/></svg>
const RadioIcon=()=> <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><circle cx="12" cy="13" r="7"/><circle cx="12" cy="13" r="2"/><path d="m7 5-2-2m10 2 2-2M12 2v3"/></svg>
const LibraryIcon=()=> <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M9 18V5l11-2v13"/><circle cx="6" cy="18" r="3"/><circle cx="17" cy="16" r="3"/></svg>
const BooksIcon=()=> <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M3 4h6a3 3 0 0 1 3 3v13a3 3 0 0 0-3-3H3V4Zm18 0h-6a3 3 0 0 0-3 3v13a3 3 0 0 1 3-3h6V4Z"/></svg>
const items:{label:string;id:NavId;Icon:ComponentType}[]=[{label:'Home',id:'home',Icon:HomeIcon},{label:'Radio',id:'radio',Icon:RadioIcon},{label:'Library',id:'library',Icon:LibraryIcon},{label:'Books',id:'bookshelf',Icon:BooksIcon}]
export default function BottomNav({currentPage,onPageChange}:{currentPage:string;onPageChange:(page:string)=>void}){return <nav style={{width:'100%',boxSizing:'border-box',display:'flex',height:72,background:'var(--bg-nav)',backdropFilter:'blur(24px)',borderTop:'1px solid var(--border-subtle)'}}>{items.map(({label,id,Icon})=>{const active=currentPage===id;return <button key={id} onClick={()=>onPageChange(id)} style={{flex:'1 1 0',minWidth:0,maxWidth:'25%',height:72,padding:'8px 0 10px',display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center',gap:4,color:active?'var(--accent-primary)':'var(--text-muted)'}}><span style={{width:26,height:26,display:'grid',placeItems:'center',position:'relative'}}>{active&&<span className="nav-active-dot"/>}<Icon/></span><span style={{fontSize:10,fontWeight:active?600:400}}>{label}</span></button>})}</nav>}

